// Objective-C API for talking to github.com/sonr-io/sonr/bind Go package.
//   gobind -lang=objc -prefix="MTR" github.com/sonr-io/sonr/bind
//
// File is generated by gobind. Do not edit.

#ifndef __MTRBind_H__
#define __MTRBind_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Address returns the address of the wallet.
 */
FOUNDATION_EXPORT NSString* _Nonnull MTRBindAddress(void);

/**
 * Broadcast broadcasts rawTx to the specified address
 */
FOUNDATION_EXPORT BOOL MTRBindBroadcast(NSString* _Nullable addr, NSData* _Nullable tx, NSError* _Nullable* _Nullable error);

/**
 * DidDoc returns the DID document as JSON
 */
FOUNDATION_EXPORT NSString* _Nonnull MTRBindDidDoc(void);

/**
 * ImportCredentials imports the given credentials into the wallet.
 */
FOUNDATION_EXPORT BOOL MTRBindImportCredential(NSData* _Nullable buf, NSError* _Nullable* _Nullable error);

/**
 * LoadWallet unmarshals the given JSON into the wallet.
 */
FOUNDATION_EXPORT BOOL MTRBindLoadWallet(NSData* _Nullable buf, NSError* _Nullable* _Nullable error);

/**
 * MarshalWallet returns the JSON representation of the wallet.
 */
FOUNDATION_EXPORT NSData* _Nullable MTRBindMarshalWallet(void);

/**
 * NewWallet creates a new mpc based wallet.
 */
FOUNDATION_EXPORT BOOL MTRBindNewWallet(NSError* _Nullable* _Nullable error);

/**
 * Sign returns the signature of the given message.
 */
FOUNDATION_EXPORT NSData* _Nullable MTRBindSign(NSString* _Nullable typeUrl, NSData* _Nullable msg, NSError* _Nullable* _Nullable error);

/**
 * Verify returns true if the given signature is valid for the given message.
 */
FOUNDATION_EXPORT BOOL MTRBindVerify(NSData* _Nullable msg, NSData* _Nullable sig);

#endif
