// Objective-C API for talking to github.com/sonr-io/sonr/bind Go package.
//   gobind -lang=objc -prefix="SNR" github.com/sonr-io/sonr/bind
//
// File is generated by gobind. Do not edit.

#ifndef __SNRMotor_H__
#define __SNRMotor_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Address returns the address of the wallet.
 */
FOUNDATION_EXPORT NSString* _Nonnull SNRMotorAddress(void);

/**
 * Broadcast broadcasts rawTx to the specified address
 */
FOUNDATION_EXPORT BOOL SNRMotorBroadcast(NSString* _Nullable addr, NSData* _Nullable tx, NSError* _Nullable* _Nullable error);

/**
 * DidDoc returns the DID document as JSON
 */
FOUNDATION_EXPORT NSString* _Nonnull SNRMotorDidDoc(void);

/**
 * ImportCredentials imports the given credentials into the wallet.
 */
FOUNDATION_EXPORT BOOL SNRMotorImportCredential(NSData* _Nullable buf, NSError* _Nullable* _Nullable error);

/**
 * LoadWallet unmarshals the given JSON into the wallet.
 */
FOUNDATION_EXPORT BOOL SNRMotorLoadWallet(NSData* _Nullable buf, NSError* _Nullable* _Nullable error);

/**
 * MarshalWallet returns the JSON representation of the wallet.
 */
FOUNDATION_EXPORT NSData* _Nullable SNRMotorMarshalWallet(void);

/**
 * NewWallet creates a new mpc based wallet.
 */
FOUNDATION_EXPORT BOOL SNRMotorNewWallet(NSError* _Nullable* _Nullable error);

/**
 * Sign returns the signature of the given message.
 */
FOUNDATION_EXPORT NSData* _Nullable SNRMotorSign(NSString* _Nullable typeUrl, NSData* _Nullable msg, NSError* _Nullable* _Nullable error);

/**
 * Verify returns true if the given signature is valid for the given message.
 */
FOUNDATION_EXPORT BOOL SNRMotorVerify(NSData* _Nullable msg, NSData* _Nullable sig);

#endif
