
// Objective-C API for talking to the following Go packages
//
//	github.com/sonr-io/sonr/bind/motor-mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __SonrMotor_FRAMEWORK_H__
#define __SonrMotor_FRAMEWORK_H__

#include "Motor.objc.h"
#include "Universe.objc.h"

#endif
